# frozen_string_literal: true

module PaginationDefaults
  DASHBOARD_COMMANDS_LIMIT = 10
  DASHBOARD_EXPORTS_LIMIT = 5
  COMMANDS_PER_PAGE = 20
  EXPORTS_QUERY_LIMIT = 20
  ORG_COMMANDS_LIMIT = 20
  ORG_SEARCH_LIMIT = 50
  ORG_SEARCH_JSON_LIMIT = 20
  RECENT_ORGS_LIMIT = 10
  FILE_PREVIEW_LIMIT = 10
  ERROR_BACKTRACE_LIMIT = 10
end
